# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConsensusService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Query_pb2 as Query__pb2
import Response_pb2 as Response__pb2
import TransactionResponse_pb2 as TransactionResponse__pb2
import Transaction_pb2 as Transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConsensusService.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16\x43onsensusService.proto\x12\x05proto\x1a\x0bQuery.proto\x1a\x0eResponse.proto\x1a\x19TransactionResponse.proto\x1a\x11Transaction.proto2\xbf\x02\n\x10\x43onsensusService\x12=\n\x0b\x63reateTopic\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12=\n\x0bupdateTopic\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12=\n\x0b\x64\x65leteTopic\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponse\x12-\n\x0cgetTopicInfo\x12\x0c.proto.Query\x1a\x0f.proto.Response\x12?\n\rsubmitMessage\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponseB\x1c\n\x1a\x63om.hedera.hashgraph.protob\x06proto3'
  ,
  dependencies=[Query__pb2.DESCRIPTOR,Response__pb2.DESCRIPTOR,TransactionResponse__pb2.DESCRIPTOR,Transaction__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_CONSENSUSSERVICE = _descriptor.ServiceDescriptor(
  name='ConsensusService',
  full_name='proto.ConsensusService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=109,
  serialized_end=428,
  methods=[
  _descriptor.MethodDescriptor(
    name='createTopic',
    full_name='proto.ConsensusService.createTopic',
    index=0,
    containing_service=None,
    input_type=Transaction__pb2._TRANSACTION,
    output_type=TransactionResponse__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='updateTopic',
    full_name='proto.ConsensusService.updateTopic',
    index=1,
    containing_service=None,
    input_type=Transaction__pb2._TRANSACTION,
    output_type=TransactionResponse__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='deleteTopic',
    full_name='proto.ConsensusService.deleteTopic',
    index=2,
    containing_service=None,
    input_type=Transaction__pb2._TRANSACTION,
    output_type=TransactionResponse__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='getTopicInfo',
    full_name='proto.ConsensusService.getTopicInfo',
    index=3,
    containing_service=None,
    input_type=Query__pb2._QUERY,
    output_type=Response__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='submitMessage',
    full_name='proto.ConsensusService.submitMessage',
    index=4,
    containing_service=None,
    input_type=Transaction__pb2._TRANSACTION,
    output_type=TransactionResponse__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CONSENSUSSERVICE)

DESCRIPTOR.services_by_name['ConsensusService'] = _CONSENSUSSERVICE

# @@protoc_insertion_point(module_scope)
