# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContractGetRecords.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2
import TransactionRecord_pb2 as TransactionRecord__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseHeader_pb2 as ResponseHeader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ContractGetRecords.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x43ontractGetRecords.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\x1a\x17TransactionRecord.proto\x1a\x11QueryHeader.proto\x1a\x14ResponseHeader.proto\"d\n\x17\x43ontractGetRecordsQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12%\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractID\"\x95\x01\n\x1a\x43ontractGetRecordsResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12%\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractID\x12)\n\x07records\x18\x03 \x03(\x0b\x32\x18.proto.TransactionRecordB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,TransactionRecord__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseHeader__pb2.DESCRIPTOR,])




_CONTRACTGETRECORDSQUERY = _descriptor.Descriptor(
  name='ContractGetRecordsQuery',
  full_name='proto.ContractGetRecordsQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.ContractGetRecordsQuery.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractID', full_name='proto.ContractGetRecordsQuery.contractID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=219,
)


_CONTRACTGETRECORDSRESPONSE = _descriptor.Descriptor(
  name='ContractGetRecordsResponse',
  full_name='proto.ContractGetRecordsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.ContractGetRecordsResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractID', full_name='proto.ContractGetRecordsResponse.contractID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='records', full_name='proto.ContractGetRecordsResponse.records', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=371,
)

_CONTRACTGETRECORDSQUERY.fields_by_name['header'].message_type = QueryHeader__pb2._QUERYHEADER
_CONTRACTGETRECORDSQUERY.fields_by_name['contractID'].message_type = BasicTypes__pb2._CONTRACTID
_CONTRACTGETRECORDSRESPONSE.fields_by_name['header'].message_type = ResponseHeader__pb2._RESPONSEHEADER
_CONTRACTGETRECORDSRESPONSE.fields_by_name['contractID'].message_type = BasicTypes__pb2._CONTRACTID
_CONTRACTGETRECORDSRESPONSE.fields_by_name['records'].message_type = TransactionRecord__pb2._TRANSACTIONRECORD
DESCRIPTOR.message_types_by_name['ContractGetRecordsQuery'] = _CONTRACTGETRECORDSQUERY
DESCRIPTOR.message_types_by_name['ContractGetRecordsResponse'] = _CONTRACTGETRECORDSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContractGetRecordsQuery = _reflection.GeneratedProtocolMessageType('ContractGetRecordsQuery', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTGETRECORDSQUERY,
  '__module__' : 'ContractGetRecords_pb2'
  # @@protoc_insertion_point(class_scope:proto.ContractGetRecordsQuery)
  })
_sym_db.RegisterMessage(ContractGetRecordsQuery)

ContractGetRecordsResponse = _reflection.GeneratedProtocolMessageType('ContractGetRecordsResponse', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTGETRECORDSRESPONSE,
  '__module__' : 'ContractGetRecords_pb2'
  # @@protoc_insertion_point(class_scope:proto.ContractGetRecordsResponse)
  })
_sym_db.RegisterMessage(ContractGetRecordsResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
