# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContractGetInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Timestamp_pb2 as Timestamp__pb2
import Duration_pb2 as Duration__pb2
import BasicTypes_pb2 as BasicTypes__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseHeader_pb2 as ResponseHeader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ContractGetInfo.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x43ontractGetInfo.proto\x12\x05proto\x1a\x0fTimestamp.proto\x1a\x0e\x44uration.proto\x1a\x10\x42\x61sicTypes.proto\x1a\x11QueryHeader.proto\x1a\x14ResponseHeader.proto\"a\n\x14\x43ontractGetInfoQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12%\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractID\"\x9d\x03\n\x17\x43ontractGetInfoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x41\n\x0c\x63ontractInfo\x18\x02 \x01(\x0b\x32+.proto.ContractGetInfoResponse.ContractInfo\x1a\x97\x02\n\x0c\x43ontractInfo\x12%\n\ncontractID\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x19\n\x11\x63ontractAccountID\x18\x03 \x01(\t\x12\x1c\n\x08\x61\x64minKey\x18\x04 \x01(\x0b\x32\n.proto.Key\x12(\n\x0e\x65xpirationTime\x18\x05 \x01(\x0b\x32\x10.proto.Timestamp\x12(\n\x0f\x61utoRenewPeriod\x18\x06 \x01(\x0b\x32\x0f.proto.Duration\x12\x0f\n\x07storage\x18\x07 \x01(\x03\x12\x0c\n\x04memo\x18\x08 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\t \x01(\x04\x42\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[Timestamp__pb2.DESCRIPTOR,Duration__pb2.DESCRIPTOR,BasicTypes__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseHeader__pb2.DESCRIPTOR,])




_CONTRACTGETINFOQUERY = _descriptor.Descriptor(
  name='ContractGetInfoQuery',
  full_name='proto.ContractGetInfoQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.ContractGetInfoQuery.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractID', full_name='proto.ContractGetInfoQuery.contractID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=221,
)


_CONTRACTGETINFORESPONSE_CONTRACTINFO = _descriptor.Descriptor(
  name='ContractInfo',
  full_name='proto.ContractGetInfoResponse.ContractInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contractID', full_name='proto.ContractGetInfoResponse.ContractInfo.contractID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accountID', full_name='proto.ContractGetInfoResponse.ContractInfo.accountID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractAccountID', full_name='proto.ContractGetInfoResponse.ContractInfo.contractAccountID', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adminKey', full_name='proto.ContractGetInfoResponse.ContractInfo.adminKey', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expirationTime', full_name='proto.ContractGetInfoResponse.ContractInfo.expirationTime', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='autoRenewPeriod', full_name='proto.ContractGetInfoResponse.ContractInfo.autoRenewPeriod', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='storage', full_name='proto.ContractGetInfoResponse.ContractInfo.storage', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='memo', full_name='proto.ContractGetInfoResponse.ContractInfo.memo', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='balance', full_name='proto.ContractGetInfoResponse.ContractInfo.balance', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=637,
)

_CONTRACTGETINFORESPONSE = _descriptor.Descriptor(
  name='ContractGetInfoResponse',
  full_name='proto.ContractGetInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.ContractGetInfoResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractInfo', full_name='proto.ContractGetInfoResponse.contractInfo', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CONTRACTGETINFORESPONSE_CONTRACTINFO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=637,
)

_CONTRACTGETINFOQUERY.fields_by_name['header'].message_type = QueryHeader__pb2._QUERYHEADER
_CONTRACTGETINFOQUERY.fields_by_name['contractID'].message_type = BasicTypes__pb2._CONTRACTID
_CONTRACTGETINFORESPONSE_CONTRACTINFO.fields_by_name['contractID'].message_type = BasicTypes__pb2._CONTRACTID
_CONTRACTGETINFORESPONSE_CONTRACTINFO.fields_by_name['accountID'].message_type = BasicTypes__pb2._ACCOUNTID
_CONTRACTGETINFORESPONSE_CONTRACTINFO.fields_by_name['adminKey'].message_type = BasicTypes__pb2._KEY
_CONTRACTGETINFORESPONSE_CONTRACTINFO.fields_by_name['expirationTime'].message_type = Timestamp__pb2._TIMESTAMP
_CONTRACTGETINFORESPONSE_CONTRACTINFO.fields_by_name['autoRenewPeriod'].message_type = Duration__pb2._DURATION
_CONTRACTGETINFORESPONSE_CONTRACTINFO.containing_type = _CONTRACTGETINFORESPONSE
_CONTRACTGETINFORESPONSE.fields_by_name['header'].message_type = ResponseHeader__pb2._RESPONSEHEADER
_CONTRACTGETINFORESPONSE.fields_by_name['contractInfo'].message_type = _CONTRACTGETINFORESPONSE_CONTRACTINFO
DESCRIPTOR.message_types_by_name['ContractGetInfoQuery'] = _CONTRACTGETINFOQUERY
DESCRIPTOR.message_types_by_name['ContractGetInfoResponse'] = _CONTRACTGETINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContractGetInfoQuery = _reflection.GeneratedProtocolMessageType('ContractGetInfoQuery', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTGETINFOQUERY,
  '__module__' : 'ContractGetInfo_pb2'
  # @@protoc_insertion_point(class_scope:proto.ContractGetInfoQuery)
  })
_sym_db.RegisterMessage(ContractGetInfoQuery)

ContractGetInfoResponse = _reflection.GeneratedProtocolMessageType('ContractGetInfoResponse', (_message.Message,), {

  'ContractInfo' : _reflection.GeneratedProtocolMessageType('ContractInfo', (_message.Message,), {
    'DESCRIPTOR' : _CONTRACTGETINFORESPONSE_CONTRACTINFO,
    '__module__' : 'ContractGetInfo_pb2'
    # @@protoc_insertion_point(class_scope:proto.ContractGetInfoResponse.ContractInfo)
    })
  ,
  'DESCRIPTOR' : _CONTRACTGETINFORESPONSE,
  '__module__' : 'ContractGetInfo_pb2'
  # @@protoc_insertion_point(class_scope:proto.ContractGetInfoResponse)
  })
_sym_db.RegisterMessage(ContractGetInfoResponse)
_sym_db.RegisterMessage(ContractGetInfoResponse.ContractInfo)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
