# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ContractCall.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ContractCall.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12\x43ontractCall.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\"}\n\x1b\x43ontractCallTransactionBody\x12%\n\ncontractID\x18\x01 \x01(\x0b\x32\x11.proto.ContractID\x12\x0b\n\x03gas\x18\x02 \x01(\x03\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x03\x12\x1a\n\x12\x66unctionParameters\x18\x04 \x01(\x0c\x42\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,])




_CONTRACTCALLTRANSACTIONBODY = _descriptor.Descriptor(
  name='ContractCallTransactionBody',
  full_name='proto.ContractCallTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='contractID', full_name='proto.ContractCallTransactionBody.contractID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gas', full_name='proto.ContractCallTransactionBody.gas', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='amount', full_name='proto.ContractCallTransactionBody.amount', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='functionParameters', full_name='proto.ContractCallTransactionBody.functionParameters', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=172,
)

_CONTRACTCALLTRANSACTIONBODY.fields_by_name['contractID'].message_type = BasicTypes__pb2._CONTRACTID
DESCRIPTOR.message_types_by_name['ContractCallTransactionBody'] = _CONTRACTCALLTRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ContractCallTransactionBody = _reflection.GeneratedProtocolMessageType('ContractCallTransactionBody', (_message.Message,), {
  'DESCRIPTOR' : _CONTRACTCALLTRANSACTIONBODY,
  '__module__' : 'ContractCall_pb2'
  # @@protoc_insertion_point(class_scope:proto.ContractCallTransactionBody)
  })
_sym_db.RegisterMessage(ContractCallTransactionBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
