# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CryptoDeleteClaim.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CryptoDeleteClaim.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x17\x43ryptoDeleteClaim.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\"i\n CryptoDeleteClaimTransactionBody\x12/\n\x15\x61\x63\x63ountIDToDeleteFrom\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x14\n\x0chashToDelete\x18\x02 \x01(\x0c\x42\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,])




_CRYPTODELETECLAIMTRANSACTIONBODY = _descriptor.Descriptor(
  name='CryptoDeleteClaimTransactionBody',
  full_name='proto.CryptoDeleteClaimTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountIDToDeleteFrom', full_name='proto.CryptoDeleteClaimTransactionBody.accountIDToDeleteFrom', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hashToDelete', full_name='proto.CryptoDeleteClaimTransactionBody.hashToDelete', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=157,
)

_CRYPTODELETECLAIMTRANSACTIONBODY.fields_by_name['accountIDToDeleteFrom'].message_type = BasicTypes__pb2._ACCOUNTID
DESCRIPTOR.message_types_by_name['CryptoDeleteClaimTransactionBody'] = _CRYPTODELETECLAIMTRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CryptoDeleteClaimTransactionBody = _reflection.GeneratedProtocolMessageType('CryptoDeleteClaimTransactionBody', (_message.Message,), {
  'DESCRIPTOR' : _CRYPTODELETECLAIMTRANSACTIONBODY,
  '__module__' : 'CryptoDeleteClaim_pb2'
  # @@protoc_insertion_point(class_scope:proto.CryptoDeleteClaimTransactionBody)
  })
_sym_db.RegisterMessage(CryptoDeleteClaimTransactionBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
