# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CryptoAddClaim.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2
import Duration_pb2 as Duration__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CryptoAddClaim.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x43ryptoAddClaim.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\x1a\x0e\x44uration.proto\"\x80\x01\n\x05\x43laim\x12#\n\taccountID\x18\x01 \x01(\x0b\x32\x10.proto.AccountID\x12\x0c\n\x04hash\x18\x02 \x01(\x0c\x12\x1c\n\x04keys\x18\x03 \x01(\x0b\x32\x0e.proto.KeyList\x12&\n\rclaimDuration\x18\x05 \x01(\x0b\x32\x0f.proto.Duration\"<\n\x1d\x43ryptoAddClaimTransactionBody\x12\x1b\n\x05\x63laim\x18\x03 \x01(\x0b\x32\x0c.proto.ClaimB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,Duration__pb2.DESCRIPTOR,])




_CLAIM = _descriptor.Descriptor(
  name='Claim',
  full_name='proto.Claim',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountID', full_name='proto.Claim.accountID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='proto.Claim.hash', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='proto.Claim.keys', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='claimDuration', full_name='proto.Claim.claimDuration', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=194,
)


_CRYPTOADDCLAIMTRANSACTIONBODY = _descriptor.Descriptor(
  name='CryptoAddClaimTransactionBody',
  full_name='proto.CryptoAddClaimTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='claim', full_name='proto.CryptoAddClaimTransactionBody.claim', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=196,
  serialized_end=256,
)

_CLAIM.fields_by_name['accountID'].message_type = BasicTypes__pb2._ACCOUNTID
_CLAIM.fields_by_name['keys'].message_type = BasicTypes__pb2._KEYLIST
_CLAIM.fields_by_name['claimDuration'].message_type = Duration__pb2._DURATION
_CRYPTOADDCLAIMTRANSACTIONBODY.fields_by_name['claim'].message_type = _CLAIM
DESCRIPTOR.message_types_by_name['Claim'] = _CLAIM
DESCRIPTOR.message_types_by_name['CryptoAddClaimTransactionBody'] = _CRYPTOADDCLAIMTRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Claim = _reflection.GeneratedProtocolMessageType('Claim', (_message.Message,), {
  'DESCRIPTOR' : _CLAIM,
  '__module__' : 'CryptoAddClaim_pb2'
  # @@protoc_insertion_point(class_scope:proto.Claim)
  })
_sym_db.RegisterMessage(Claim)

CryptoAddClaimTransactionBody = _reflection.GeneratedProtocolMessageType('CryptoAddClaimTransactionBody', (_message.Message,), {
  'DESCRIPTOR' : _CRYPTOADDCLAIMTRANSACTIONBODY,
  '__module__' : 'CryptoAddClaim_pb2'
  # @@protoc_insertion_point(class_scope:proto.CryptoAddClaimTransactionBody)
  })
_sym_db.RegisterMessage(CryptoAddClaimTransactionBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
