# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CryptoGetClaim.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseHeader_pb2 as ResponseHeader__pb2
import CryptoAddClaim_pb2 as CryptoAddClaim__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='CryptoGetClaim.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14\x43ryptoGetClaim.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\x1a\x11QueryHeader.proto\x1a\x14ResponseHeader.proto\x1a\x14\x43ryptoAddClaim.proto\"l\n\x13\x43ryptoGetClaimQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x0c\n\x04hash\x18\x03 \x01(\x0c\"\\\n\x16\x43ryptoGetClaimResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x1b\n\x05\x63laim\x18\x02 \x01(\x0b\x32\x0c.proto.ClaimB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseHeader__pb2.DESCRIPTOR,CryptoAddClaim__pb2.DESCRIPTOR,])




_CRYPTOGETCLAIMQUERY = _descriptor.Descriptor(
  name='CryptoGetClaimQuery',
  full_name='proto.CryptoGetClaimQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.CryptoGetClaimQuery.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accountID', full_name='proto.CryptoGetClaimQuery.accountID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hash', full_name='proto.CryptoGetClaimQuery.hash', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=220,
)


_CRYPTOGETCLAIMRESPONSE = _descriptor.Descriptor(
  name='CryptoGetClaimResponse',
  full_name='proto.CryptoGetClaimResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.CryptoGetClaimResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='claim', full_name='proto.CryptoGetClaimResponse.claim', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=314,
)

_CRYPTOGETCLAIMQUERY.fields_by_name['header'].message_type = QueryHeader__pb2._QUERYHEADER
_CRYPTOGETCLAIMQUERY.fields_by_name['accountID'].message_type = BasicTypes__pb2._ACCOUNTID
_CRYPTOGETCLAIMRESPONSE.fields_by_name['header'].message_type = ResponseHeader__pb2._RESPONSEHEADER
_CRYPTOGETCLAIMRESPONSE.fields_by_name['claim'].message_type = CryptoAddClaim__pb2._CLAIM
DESCRIPTOR.message_types_by_name['CryptoGetClaimQuery'] = _CRYPTOGETCLAIMQUERY
DESCRIPTOR.message_types_by_name['CryptoGetClaimResponse'] = _CRYPTOGETCLAIMRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CryptoGetClaimQuery = _reflection.GeneratedProtocolMessageType('CryptoGetClaimQuery', (_message.Message,), {
  'DESCRIPTOR' : _CRYPTOGETCLAIMQUERY,
  '__module__' : 'CryptoGetClaim_pb2'
  # @@protoc_insertion_point(class_scope:proto.CryptoGetClaimQuery)
  })
_sym_db.RegisterMessage(CryptoGetClaimQuery)

CryptoGetClaimResponse = _reflection.GeneratedProtocolMessageType('CryptoGetClaimResponse', (_message.Message,), {
  'DESCRIPTOR' : _CRYPTOGETCLAIMRESPONSE,
  '__module__' : 'CryptoGetClaim_pb2'
  # @@protoc_insertion_point(class_scope:proto.CryptoGetClaimResponse)
  })
_sym_db.RegisterMessage(CryptoGetClaimResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
