# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileCreate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2
import Timestamp_pb2 as Timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='FileCreate.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10\x46ileCreate.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\x1a\x0fTimestamp.proto\"\xdd\x01\n\x19\x46ileCreateTransactionBody\x12(\n\x0e\x65xpirationTime\x18\x02 \x01(\x0b\x32\x10.proto.Timestamp\x12\x1c\n\x04keys\x18\x03 \x01(\x0b\x32\x0e.proto.KeyList\x12\x10\n\x08\x63ontents\x18\x04 \x01(\x0c\x12\x1f\n\x07shardID\x18\x05 \x01(\x0b\x32\x0e.proto.ShardID\x12\x1f\n\x07realmID\x18\x06 \x01(\x0b\x32\x0e.proto.RealmID\x12$\n\x10newRealmAdminKey\x18\x07 \x01(\x0b\x32\n.proto.KeyB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,Timestamp__pb2.DESCRIPTOR,])




_FILECREATETRANSACTIONBODY = _descriptor.Descriptor(
  name='FileCreateTransactionBody',
  full_name='proto.FileCreateTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='expirationTime', full_name='proto.FileCreateTransactionBody.expirationTime', index=0,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='keys', full_name='proto.FileCreateTransactionBody.keys', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contents', full_name='proto.FileCreateTransactionBody.contents', index=2,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shardID', full_name='proto.FileCreateTransactionBody.shardID', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='realmID', full_name='proto.FileCreateTransactionBody.realmID', index=4,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='newRealmAdminKey', full_name='proto.FileCreateTransactionBody.newRealmAdminKey', index=5,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=284,
)

_FILECREATETRANSACTIONBODY.fields_by_name['expirationTime'].message_type = Timestamp__pb2._TIMESTAMP
_FILECREATETRANSACTIONBODY.fields_by_name['keys'].message_type = BasicTypes__pb2._KEYLIST
_FILECREATETRANSACTIONBODY.fields_by_name['shardID'].message_type = BasicTypes__pb2._SHARDID
_FILECREATETRANSACTIONBODY.fields_by_name['realmID'].message_type = BasicTypes__pb2._REALMID
_FILECREATETRANSACTIONBODY.fields_by_name['newRealmAdminKey'].message_type = BasicTypes__pb2._KEY
DESCRIPTOR.message_types_by_name['FileCreateTransactionBody'] = _FILECREATETRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileCreateTransactionBody = _reflection.GeneratedProtocolMessageType('FileCreateTransactionBody', (_message.Message,), {
  'DESCRIPTOR' : _FILECREATETRANSACTIONBODY,
  '__module__' : 'FileCreate_pb2'
  # @@protoc_insertion_point(class_scope:proto.FileCreateTransactionBody)
  })
_sym_db.RegisterMessage(FileCreateTransactionBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
