# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FileGetContents.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseHeader_pb2 as ResponseHeader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='FileGetContents.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15\x46ileGetContents.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\x1a\x11QueryHeader.proto\x1a\x14ResponseHeader.proto\"Y\n\x14\x46ileGetContentsQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12\x1d\n\x06\x66ileID\x18\x02 \x01(\x0b\x32\r.proto.FileID\"\xc4\x01\n\x17\x46ileGetContentsResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x41\n\x0c\x66ileContents\x18\x02 \x01(\x0b\x32+.proto.FileGetContentsResponse.FileContents\x1a?\n\x0c\x46ileContents\x12\x1d\n\x06\x66ileID\x18\x01 \x01(\x0b\x32\r.proto.FileID\x12\x10\n\x08\x63ontents\x18\x02 \x01(\x0c\x42\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseHeader__pb2.DESCRIPTOR,])




_FILEGETCONTENTSQUERY = _descriptor.Descriptor(
  name='FileGetContentsQuery',
  full_name='proto.FileGetContentsQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.FileGetContentsQuery.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileID', full_name='proto.FileGetContentsQuery.fileID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=180,
)


_FILEGETCONTENTSRESPONSE_FILECONTENTS = _descriptor.Descriptor(
  name='FileContents',
  full_name='proto.FileGetContentsResponse.FileContents',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileID', full_name='proto.FileGetContentsResponse.FileContents.fileID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contents', full_name='proto.FileGetContentsResponse.FileContents.contents', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=379,
)

_FILEGETCONTENTSRESPONSE = _descriptor.Descriptor(
  name='FileGetContentsResponse',
  full_name='proto.FileGetContentsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.FileGetContentsResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileContents', full_name='proto.FileGetContentsResponse.fileContents', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_FILEGETCONTENTSRESPONSE_FILECONTENTS, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=379,
)

_FILEGETCONTENTSQUERY.fields_by_name['header'].message_type = QueryHeader__pb2._QUERYHEADER
_FILEGETCONTENTSQUERY.fields_by_name['fileID'].message_type = BasicTypes__pb2._FILEID
_FILEGETCONTENTSRESPONSE_FILECONTENTS.fields_by_name['fileID'].message_type = BasicTypes__pb2._FILEID
_FILEGETCONTENTSRESPONSE_FILECONTENTS.containing_type = _FILEGETCONTENTSRESPONSE
_FILEGETCONTENTSRESPONSE.fields_by_name['header'].message_type = ResponseHeader__pb2._RESPONSEHEADER
_FILEGETCONTENTSRESPONSE.fields_by_name['fileContents'].message_type = _FILEGETCONTENTSRESPONSE_FILECONTENTS
DESCRIPTOR.message_types_by_name['FileGetContentsQuery'] = _FILEGETCONTENTSQUERY
DESCRIPTOR.message_types_by_name['FileGetContentsResponse'] = _FILEGETCONTENTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileGetContentsQuery = _reflection.GeneratedProtocolMessageType('FileGetContentsQuery', (_message.Message,), {
  'DESCRIPTOR' : _FILEGETCONTENTSQUERY,
  '__module__' : 'FileGetContents_pb2'
  # @@protoc_insertion_point(class_scope:proto.FileGetContentsQuery)
  })
_sym_db.RegisterMessage(FileGetContentsQuery)

FileGetContentsResponse = _reflection.GeneratedProtocolMessageType('FileGetContentsResponse', (_message.Message,), {

  'FileContents' : _reflection.GeneratedProtocolMessageType('FileContents', (_message.Message,), {
    'DESCRIPTOR' : _FILEGETCONTENTSRESPONSE_FILECONTENTS,
    '__module__' : 'FileGetContents_pb2'
    # @@protoc_insertion_point(class_scope:proto.FileGetContentsResponse.FileContents)
    })
  ,
  'DESCRIPTOR' : _FILEGETCONTENTSRESPONSE,
  '__module__' : 'FileGetContents_pb2'
  # @@protoc_insertion_point(class_scope:proto.FileGetContentsResponse)
  })
_sym_db.RegisterMessage(FileGetContentsResponse)
_sym_db.RegisterMessage(FileGetContentsResponse.FileContents)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
