# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FreezeService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransactionResponse_pb2 as TransactionResponse__pb2
import Transaction_pb2 as Transaction__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='FreezeService.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x46reezeService.proto\x12\x05proto\x1a\x19TransactionResponse.proto\x1a\x11Transaction.proto2I\n\rFreezeService\x12\x38\n\x06\x66reeze\x12\x12.proto.Transaction\x1a\x1a.proto.TransactionResponseB\x1c\n\x1a\x63om.hedera.hashgraph.protob\x06proto3'
  ,
  dependencies=[TransactionResponse__pb2.DESCRIPTOR,Transaction__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_FREEZESERVICE = _descriptor.ServiceDescriptor(
  name='FreezeService',
  full_name='proto.FreezeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=76,
  serialized_end=149,
  methods=[
  _descriptor.MethodDescriptor(
    name='freeze',
    full_name='proto.FreezeService.freeze',
    index=0,
    containing_service=None,
    input_type=Transaction__pb2._TRANSACTION,
    output_type=TransactionResponse__pb2._TRANSACTIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FREEZESERVICE)

DESCRIPTOR.services_by_name['FreezeService'] = _FREEZESERVICE

# @@protoc_insertion_point(module_scope)
