# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Freeze.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Duration_pb2 as Duration__pb2
import Timestamp_pb2 as Timestamp__pb2
import BasicTypes_pb2 as BasicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Freeze.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x46reeze.proto\x12\x05proto\x1a\x0e\x44uration.proto\x1a\x0fTimestamp.proto\x1a\x10\x42\x61sicTypes.proto\"\x80\x01\n\x15\x46reezeTransactionBody\x12\x11\n\tstartHour\x18\x01 \x01(\x05\x12\x10\n\x08startMin\x18\x02 \x01(\x05\x12\x0f\n\x07\x65ndHour\x18\x03 \x01(\x05\x12\x0e\n\x06\x65ndMin\x18\x04 \x01(\x05\x12!\n\nupdateFile\x18\x05 \x01(\x0b\x32\r.proto.FileIDB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[Duration__pb2.DESCRIPTOR,Timestamp__pb2.DESCRIPTOR,BasicTypes__pb2.DESCRIPTOR,])




_FREEZETRANSACTIONBODY = _descriptor.Descriptor(
  name='FreezeTransactionBody',
  full_name='proto.FreezeTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='startHour', full_name='proto.FreezeTransactionBody.startHour', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='startMin', full_name='proto.FreezeTransactionBody.startMin', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endHour', full_name='proto.FreezeTransactionBody.endHour', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='endMin', full_name='proto.FreezeTransactionBody.endMin', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='updateFile', full_name='proto.FreezeTransactionBody.updateFile', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=203,
)

_FREEZETRANSACTIONBODY.fields_by_name['updateFile'].message_type = BasicTypes__pb2._FILEID
DESCRIPTOR.message_types_by_name['FreezeTransactionBody'] = _FREEZETRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FreezeTransactionBody = _reflection.GeneratedProtocolMessageType('FreezeTransactionBody', (_message.Message,), {
  'DESCRIPTOR' : _FREEZETRANSACTIONBODY,
  '__module__' : 'Freeze_pb2'
  # @@protoc_insertion_point(class_scope:proto.FreezeTransactionBody)
  })
_sym_db.RegisterMessage(FreezeTransactionBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
