# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetByKey.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseHeader_pb2 as ResponseHeader__pb2
import CryptoAddLiveHash_pb2 as CryptoAddLiveHash__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='GetByKey.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0eGetByKey.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\x1a\x11QueryHeader.proto\x1a\x14ResponseHeader.proto\x1a\x17\x43ryptoAddLiveHash.proto\"L\n\rGetByKeyQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12\x17\n\x03key\x18\x02 \x01(\x0b\x32\n.proto.Key\"\xaa\x01\n\x08\x45ntityID\x12%\n\taccountID\x18\x01 \x01(\x0b\x32\x10.proto.AccountIDH\x00\x12#\n\x08liveHash\x18\x02 \x01(\x0b\x32\x0f.proto.LiveHashH\x00\x12\x1f\n\x06\x66ileID\x18\x03 \x01(\x0b\x32\r.proto.FileIDH\x00\x12\'\n\ncontractID\x18\x04 \x01(\x0b\x32\x11.proto.ContractIDH\x00\x42\x08\n\x06\x65ntity\"\\\n\x10GetByKeyResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12!\n\x08\x65ntities\x18\x02 \x03(\x0b\x32\x0f.proto.EntityIDB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseHeader__pb2.DESCRIPTOR,CryptoAddLiveHash__pb2.DESCRIPTOR,])




_GETBYKEYQUERY = _descriptor.Descriptor(
  name='GetByKeyQuery',
  full_name='proto.GetByKeyQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.GetByKeyQuery.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='key', full_name='proto.GetByKeyQuery.key', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=185,
)


_ENTITYID = _descriptor.Descriptor(
  name='EntityID',
  full_name='proto.EntityID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountID', full_name='proto.EntityID.accountID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='liveHash', full_name='proto.EntityID.liveHash', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileID', full_name='proto.EntityID.fileID', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractID', full_name='proto.EntityID.contractID', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='entity', full_name='proto.EntityID.entity',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=188,
  serialized_end=358,
)


_GETBYKEYRESPONSE = _descriptor.Descriptor(
  name='GetByKeyResponse',
  full_name='proto.GetByKeyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.GetByKeyResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='entities', full_name='proto.GetByKeyResponse.entities', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=360,
  serialized_end=452,
)

_GETBYKEYQUERY.fields_by_name['header'].message_type = QueryHeader__pb2._QUERYHEADER
_GETBYKEYQUERY.fields_by_name['key'].message_type = BasicTypes__pb2._KEY
_ENTITYID.fields_by_name['accountID'].message_type = BasicTypes__pb2._ACCOUNTID
_ENTITYID.fields_by_name['liveHash'].message_type = CryptoAddLiveHash__pb2._LIVEHASH
_ENTITYID.fields_by_name['fileID'].message_type = BasicTypes__pb2._FILEID
_ENTITYID.fields_by_name['contractID'].message_type = BasicTypes__pb2._CONTRACTID
_ENTITYID.oneofs_by_name['entity'].fields.append(
  _ENTITYID.fields_by_name['accountID'])
_ENTITYID.fields_by_name['accountID'].containing_oneof = _ENTITYID.oneofs_by_name['entity']
_ENTITYID.oneofs_by_name['entity'].fields.append(
  _ENTITYID.fields_by_name['liveHash'])
_ENTITYID.fields_by_name['liveHash'].containing_oneof = _ENTITYID.oneofs_by_name['entity']
_ENTITYID.oneofs_by_name['entity'].fields.append(
  _ENTITYID.fields_by_name['fileID'])
_ENTITYID.fields_by_name['fileID'].containing_oneof = _ENTITYID.oneofs_by_name['entity']
_ENTITYID.oneofs_by_name['entity'].fields.append(
  _ENTITYID.fields_by_name['contractID'])
_ENTITYID.fields_by_name['contractID'].containing_oneof = _ENTITYID.oneofs_by_name['entity']
_GETBYKEYRESPONSE.fields_by_name['header'].message_type = ResponseHeader__pb2._RESPONSEHEADER
_GETBYKEYRESPONSE.fields_by_name['entities'].message_type = _ENTITYID
DESCRIPTOR.message_types_by_name['GetByKeyQuery'] = _GETBYKEYQUERY
DESCRIPTOR.message_types_by_name['EntityID'] = _ENTITYID
DESCRIPTOR.message_types_by_name['GetByKeyResponse'] = _GETBYKEYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetByKeyQuery = _reflection.GeneratedProtocolMessageType('GetByKeyQuery', (_message.Message,), {
  'DESCRIPTOR' : _GETBYKEYQUERY,
  '__module__' : 'GetByKey_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetByKeyQuery)
  })
_sym_db.RegisterMessage(GetByKeyQuery)

EntityID = _reflection.GeneratedProtocolMessageType('EntityID', (_message.Message,), {
  'DESCRIPTOR' : _ENTITYID,
  '__module__' : 'GetByKey_pb2'
  # @@protoc_insertion_point(class_scope:proto.EntityID)
  })
_sym_db.RegisterMessage(EntityID)

GetByKeyResponse = _reflection.GeneratedProtocolMessageType('GetByKeyResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBYKEYRESPONSE,
  '__module__' : 'GetByKey_pb2'
  # @@protoc_insertion_point(class_scope:proto.GetByKeyResponse)
  })
_sym_db.RegisterMessage(GetByKeyResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
