# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NetworkGetVersionInfo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseHeader_pb2 as ResponseHeader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NetworkGetVersionInfo.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bNetworkGetVersionInfo.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\x1a\x11QueryHeader.proto\x1a\x14ResponseHeader.proto\"@\n\x1aNetworkGetVersionInfoQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\"\xaf\x01\n\x1dNetworkGetVersionInfoResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x30\n\x10hapiProtoVersion\x18\x02 \x01(\x0b\x32\x16.proto.SemanticVersion\x12\x35\n\x15hederaServicesVersion\x18\x03 \x01(\x0b\x32\x16.proto.SemanticVersionB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseHeader__pb2.DESCRIPTOR,])




_NETWORKGETVERSIONINFOQUERY = _descriptor.Descriptor(
  name='NetworkGetVersionInfoQuery',
  full_name='proto.NetworkGetVersionInfoQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.NetworkGetVersionInfoQuery.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=161,
)


_NETWORKGETVERSIONINFORESPONSE = _descriptor.Descriptor(
  name='NetworkGetVersionInfoResponse',
  full_name='proto.NetworkGetVersionInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.NetworkGetVersionInfoResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hapiProtoVersion', full_name='proto.NetworkGetVersionInfoResponse.hapiProtoVersion', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hederaServicesVersion', full_name='proto.NetworkGetVersionInfoResponse.hederaServicesVersion', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=339,
)

_NETWORKGETVERSIONINFOQUERY.fields_by_name['header'].message_type = QueryHeader__pb2._QUERYHEADER
_NETWORKGETVERSIONINFORESPONSE.fields_by_name['header'].message_type = ResponseHeader__pb2._RESPONSEHEADER
_NETWORKGETVERSIONINFORESPONSE.fields_by_name['hapiProtoVersion'].message_type = BasicTypes__pb2._SEMANTICVERSION
_NETWORKGETVERSIONINFORESPONSE.fields_by_name['hederaServicesVersion'].message_type = BasicTypes__pb2._SEMANTICVERSION
DESCRIPTOR.message_types_by_name['NetworkGetVersionInfoQuery'] = _NETWORKGETVERSIONINFOQUERY
DESCRIPTOR.message_types_by_name['NetworkGetVersionInfoResponse'] = _NETWORKGETVERSIONINFORESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NetworkGetVersionInfoQuery = _reflection.GeneratedProtocolMessageType('NetworkGetVersionInfoQuery', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKGETVERSIONINFOQUERY,
  '__module__' : 'NetworkGetVersionInfo_pb2'
  # @@protoc_insertion_point(class_scope:proto.NetworkGetVersionInfoQuery)
  })
_sym_db.RegisterMessage(NetworkGetVersionInfoQuery)

NetworkGetVersionInfoResponse = _reflection.GeneratedProtocolMessageType('NetworkGetVersionInfoResponse', (_message.Message,), {
  'DESCRIPTOR' : _NETWORKGETVERSIONINFORESPONSE,
  '__module__' : 'NetworkGetVersionInfo_pb2'
  # @@protoc_insertion_point(class_scope:proto.NetworkGetVersionInfoResponse)
  })
_sym_db.RegisterMessage(NetworkGetVersionInfoResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
