# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NetworkService.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Query_pb2 as Query__pb2
import Response_pb2 as Response__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='NetworkService.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14NetworkService.proto\x12\x05proto\x1a\x0bQuery.proto\x1a\x0eResponse.proto2A\n\x0eNetworkService\x12/\n\x0egetVersionInfo\x12\x0c.proto.Query\x1a\x0f.proto.ResponseB\x1c\n\x1a\x63om.hedera.hashgraph.protob\x06proto3'
  ,
  dependencies=[Query__pb2.DESCRIPTOR,Response__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_NETWORKSERVICE = _descriptor.ServiceDescriptor(
  name='NetworkService',
  full_name='proto.NetworkService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=60,
  serialized_end=125,
  methods=[
  _descriptor.MethodDescriptor(
    name='getVersionInfo',
    full_name='proto.NetworkService.getVersionInfo',
    index=0,
    containing_service=None,
    input_type=Query__pb2._QUERY,
    output_type=Response__pb2._RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETWORKSERVICE)

DESCRIPTOR.services_by_name['NetworkService'] = _NETWORKSERVICE

# @@protoc_insertion_point(module_scope)
