# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResponseHeader.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransactionResponse_pb2 as TransactionResponse__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseCode_pb2 as ResponseCode__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResponseHeader.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14ResponseHeader.proto\x12\x05proto\x1a\x19TransactionResponse.proto\x1a\x11QueryHeader.proto\x1a\x12ResponseCode.proto\"\x9b\x01\n\x0eResponseHeader\x12<\n\x1bnodeTransactionPrecheckCode\x18\x01 \x01(\x0e\x32\x17.proto.ResponseCodeEnum\x12)\n\x0cresponseType\x18\x02 \x01(\x0e\x32\x13.proto.ResponseType\x12\x0c\n\x04\x63ost\x18\x03 \x01(\x04\x12\x12\n\nstateProof\x18\x04 \x01(\x0c\x42\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[TransactionResponse__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseCode__pb2.DESCRIPTOR,])




_RESPONSEHEADER = _descriptor.Descriptor(
  name='ResponseHeader',
  full_name='proto.ResponseHeader',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeTransactionPrecheckCode', full_name='proto.ResponseHeader.nodeTransactionPrecheckCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='responseType', full_name='proto.ResponseHeader.responseType', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cost', full_name='proto.ResponseHeader.cost', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stateProof', full_name='proto.ResponseHeader.stateProof', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=98,
  serialized_end=253,
)

_RESPONSEHEADER.fields_by_name['nodeTransactionPrecheckCode'].enum_type = ResponseCode__pb2._RESPONSECODEENUM
_RESPONSEHEADER.fields_by_name['responseType'].enum_type = QueryHeader__pb2._RESPONSETYPE
DESCRIPTOR.message_types_by_name['ResponseHeader'] = _RESPONSEHEADER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResponseHeader = _reflection.GeneratedProtocolMessageType('ResponseHeader', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEHEADER,
  '__module__' : 'ResponseHeader_pb2'
  # @@protoc_insertion_point(class_scope:proto.ResponseHeader)
  })
_sym_db.RegisterMessage(ResponseHeader)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
