# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SystemUndelete.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SystemUndelete.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14SystemUndelete.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\"o\n\x1dSystemUndeleteTransactionBody\x12\x1f\n\x06\x66ileID\x18\x01 \x01(\x0b\x32\r.proto.FileIDH\x00\x12\'\n\ncontractID\x18\x02 \x01(\x0b\x32\x11.proto.ContractIDH\x00\x42\x04\n\x02idB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,])




_SYSTEMUNDELETETRANSACTIONBODY = _descriptor.Descriptor(
  name='SystemUndeleteTransactionBody',
  full_name='proto.SystemUndeleteTransactionBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fileID', full_name='proto.SystemUndeleteTransactionBody.fileID', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractID', full_name='proto.SystemUndeleteTransactionBody.contractID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='id', full_name='proto.SystemUndeleteTransactionBody.id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=49,
  serialized_end=160,
)

_SYSTEMUNDELETETRANSACTIONBODY.fields_by_name['fileID'].message_type = BasicTypes__pb2._FILEID
_SYSTEMUNDELETETRANSACTIONBODY.fields_by_name['contractID'].message_type = BasicTypes__pb2._CONTRACTID
_SYSTEMUNDELETETRANSACTIONBODY.oneofs_by_name['id'].fields.append(
  _SYSTEMUNDELETETRANSACTIONBODY.fields_by_name['fileID'])
_SYSTEMUNDELETETRANSACTIONBODY.fields_by_name['fileID'].containing_oneof = _SYSTEMUNDELETETRANSACTIONBODY.oneofs_by_name['id']
_SYSTEMUNDELETETRANSACTIONBODY.oneofs_by_name['id'].fields.append(
  _SYSTEMUNDELETETRANSACTIONBODY.fields_by_name['contractID'])
_SYSTEMUNDELETETRANSACTIONBODY.fields_by_name['contractID'].containing_oneof = _SYSTEMUNDELETETRANSACTIONBODY.oneofs_by_name['id']
DESCRIPTOR.message_types_by_name['SystemUndeleteTransactionBody'] = _SYSTEMUNDELETETRANSACTIONBODY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SystemUndeleteTransactionBody = _reflection.GeneratedProtocolMessageType('SystemUndeleteTransactionBody', (_message.Message,), {
  'DESCRIPTOR' : _SYSTEMUNDELETETRANSACTIONBODY,
  '__module__' : 'SystemUndelete_pb2'
  # @@protoc_insertion_point(class_scope:proto.SystemUndeleteTransactionBody)
  })
_sym_db.RegisterMessage(SystemUndeleteTransactionBody)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
