# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Transaction.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import Duration_pb2 as Duration__pb2
import BasicTypes_pb2 as BasicTypes__pb2
import TransactionBody_pb2 as TransactionBody__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Transaction.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11Transaction.proto\x12\x05proto\x1a\x0e\x44uration.proto\x1a\x10\x42\x61sicTypes.proto\x1a\x15TransactionBody.proto\"\xa7\x01\n\x0bTransaction\x12*\n\x04\x62ody\x18\x01 \x01(\x0b\x32\x16.proto.TransactionBodyB\x02\x18\x01H\x00\x12\x13\n\tbodyBytes\x18\x04 \x01(\x0cH\x00\x12&\n\x04sigs\x18\x02 \x01(\x0b\x32\x14.proto.SignatureListB\x02\x18\x01\x12#\n\x06sigMap\x18\x03 \x01(\x0b\x32\x13.proto.SignatureMapB\n\n\x08\x62odyDataB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[Duration__pb2.DESCRIPTOR,BasicTypes__pb2.DESCRIPTOR,TransactionBody__pb2.DESCRIPTOR,])




_TRANSACTION = _descriptor.Descriptor(
  name='Transaction',
  full_name='proto.Transaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='body', full_name='proto.Transaction.body', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bodyBytes', full_name='proto.Transaction.bodyBytes', index=1,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sigs', full_name='proto.Transaction.sigs', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\030\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sigMap', full_name='proto.Transaction.sigMap', index=3,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='bodyData', full_name='proto.Transaction.bodyData',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=86,
  serialized_end=253,
)

_TRANSACTION.fields_by_name['body'].message_type = TransactionBody__pb2._TRANSACTIONBODY
_TRANSACTION.fields_by_name['sigs'].message_type = BasicTypes__pb2._SIGNATURELIST
_TRANSACTION.fields_by_name['sigMap'].message_type = BasicTypes__pb2._SIGNATUREMAP
_TRANSACTION.oneofs_by_name['bodyData'].fields.append(
  _TRANSACTION.fields_by_name['body'])
_TRANSACTION.fields_by_name['body'].containing_oneof = _TRANSACTION.oneofs_by_name['bodyData']
_TRANSACTION.oneofs_by_name['bodyData'].fields.append(
  _TRANSACTION.fields_by_name['bodyBytes'])
_TRANSACTION.fields_by_name['bodyBytes'].containing_oneof = _TRANSACTION.oneofs_by_name['bodyData']
DESCRIPTOR.message_types_by_name['Transaction'] = _TRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Transaction = _reflection.GeneratedProtocolMessageType('Transaction', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTION,
  '__module__' : 'Transaction_pb2'
  # @@protoc_insertion_point(class_scope:proto.Transaction)
  })
_sym_db.RegisterMessage(Transaction)


DESCRIPTOR._options = None
_TRANSACTION.fields_by_name['body']._options = None
_TRANSACTION.fields_by_name['sigs']._options = None
# @@protoc_insertion_point(module_scope)
