# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionResponse.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ResponseCode_pb2 as ResponseCode__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TransactionResponse.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19TransactionResponse.proto\x12\x05proto\x1a\x12ResponseCode.proto\"a\n\x13TransactionResponse\x12<\n\x1bnodeTransactionPrecheckCode\x18\x01 \x01(\x0e\x32\x17.proto.ResponseCodeEnum\x12\x0c\n\x04\x63ost\x18\x02 \x01(\x04\x42\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[ResponseCode__pb2.DESCRIPTOR,])




_TRANSACTIONRESPONSE = _descriptor.Descriptor(
  name='TransactionResponse',
  full_name='proto.TransactionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nodeTransactionPrecheckCode', full_name='proto.TransactionResponse.nodeTransactionPrecheckCode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cost', full_name='proto.TransactionResponse.cost', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=153,
)

_TRANSACTIONRESPONSE.fields_by_name['nodeTransactionPrecheckCode'].enum_type = ResponseCode__pb2._RESPONSECODEENUM
DESCRIPTOR.message_types_by_name['TransactionResponse'] = _TRANSACTIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionResponse = _reflection.GeneratedProtocolMessageType('TransactionResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONRESPONSE,
  '__module__' : 'TransactionResponse_pb2'
  # @@protoc_insertion_point(class_scope:proto.TransactionResponse)
  })
_sym_db.RegisterMessage(TransactionResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
