# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionGetReceipt.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransactionReceipt_pb2 as TransactionReceipt__pb2
import BasicTypes_pb2 as BasicTypes__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseHeader_pb2 as ResponseHeader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TransactionGetReceipt.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1bTransactionGetReceipt.proto\x12\x05proto\x1a\x18TransactionReceipt.proto\x1a\x10\x42\x61sicTypes.proto\x1a\x11QueryHeader.proto\x1a\x14ResponseHeader.proto\"m\n\x1aTransactionGetReceiptQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12+\n\rtransactionID\x18\x02 \x01(\x0b\x32\x14.proto.TransactionID\"r\n\x1dTransactionGetReceiptResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12*\n\x07receipt\x18\x02 \x01(\x0b\x32\x19.proto.TransactionReceiptB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[TransactionReceipt__pb2.DESCRIPTOR,BasicTypes__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseHeader__pb2.DESCRIPTOR,])




_TRANSACTIONGETRECEIPTQUERY = _descriptor.Descriptor(
  name='TransactionGetReceiptQuery',
  full_name='proto.TransactionGetReceiptQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.TransactionGetReceiptQuery.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='proto.TransactionGetReceiptQuery.transactionID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=232,
)


_TRANSACTIONGETRECEIPTRESPONSE = _descriptor.Descriptor(
  name='TransactionGetReceiptResponse',
  full_name='proto.TransactionGetReceiptResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.TransactionGetReceiptResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receipt', full_name='proto.TransactionGetReceiptResponse.receipt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=234,
  serialized_end=348,
)

_TRANSACTIONGETRECEIPTQUERY.fields_by_name['header'].message_type = QueryHeader__pb2._QUERYHEADER
_TRANSACTIONGETRECEIPTQUERY.fields_by_name['transactionID'].message_type = BasicTypes__pb2._TRANSACTIONID
_TRANSACTIONGETRECEIPTRESPONSE.fields_by_name['header'].message_type = ResponseHeader__pb2._RESPONSEHEADER
_TRANSACTIONGETRECEIPTRESPONSE.fields_by_name['receipt'].message_type = TransactionReceipt__pb2._TRANSACTIONRECEIPT
DESCRIPTOR.message_types_by_name['TransactionGetReceiptQuery'] = _TRANSACTIONGETRECEIPTQUERY
DESCRIPTOR.message_types_by_name['TransactionGetReceiptResponse'] = _TRANSACTIONGETRECEIPTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionGetReceiptQuery = _reflection.GeneratedProtocolMessageType('TransactionGetReceiptQuery', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONGETRECEIPTQUERY,
  '__module__' : 'TransactionGetReceipt_pb2'
  # @@protoc_insertion_point(class_scope:proto.TransactionGetReceiptQuery)
  })
_sym_db.RegisterMessage(TransactionGetReceiptQuery)

TransactionGetReceiptResponse = _reflection.GeneratedProtocolMessageType('TransactionGetReceiptResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONGETRECEIPTRESPONSE,
  '__module__' : 'TransactionGetReceipt_pb2'
  # @@protoc_insertion_point(class_scope:proto.TransactionGetReceiptResponse)
  })
_sym_db.RegisterMessage(TransactionGetReceiptResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
