# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionReceipt.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import BasicTypes_pb2 as BasicTypes__pb2
import ResponseCode_pb2 as ResponseCode__pb2
import ExchangeRate_pb2 as ExchangeRate__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TransactionReceipt.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18TransactionReceipt.proto\x12\x05proto\x1a\x10\x42\x61sicTypes.proto\x1a\x12ResponseCode.proto\x1a\x12\x45xchangeRate.proto\"\xcf\x02\n\x12TransactionReceipt\x12\'\n\x06status\x18\x01 \x01(\x0e\x32\x17.proto.ResponseCodeEnum\x12#\n\taccountID\x18\x02 \x01(\x0b\x32\x10.proto.AccountID\x12\x1d\n\x06\x66ileID\x18\x03 \x01(\x0b\x32\r.proto.FileID\x12%\n\ncontractID\x18\x04 \x01(\x0b\x32\x11.proto.ContractID\x12,\n\x0c\x65xchangeRate\x18\x05 \x01(\x0b\x32\x16.proto.ExchangeRateSet\x12\x1f\n\x07topicID\x18\x06 \x01(\x0b\x32\x0e.proto.TopicID\x12\x1b\n\x13topicSequenceNumber\x18\x07 \x01(\x04\x12\x18\n\x10topicRunningHash\x18\x08 \x01(\x0c\x12\x1f\n\x17topicRunningHashVersion\x18\t \x01(\x04\x42\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[BasicTypes__pb2.DESCRIPTOR,ResponseCode__pb2.DESCRIPTOR,ExchangeRate__pb2.DESCRIPTOR,])




_TRANSACTIONRECEIPT = _descriptor.Descriptor(
  name='TransactionReceipt',
  full_name='proto.TransactionReceipt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='proto.TransactionReceipt.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='accountID', full_name='proto.TransactionReceipt.accountID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fileID', full_name='proto.TransactionReceipt.fileID', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contractID', full_name='proto.TransactionReceipt.contractID', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='exchangeRate', full_name='proto.TransactionReceipt.exchangeRate', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topicID', full_name='proto.TransactionReceipt.topicID', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topicSequenceNumber', full_name='proto.TransactionReceipt.topicSequenceNumber', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topicRunningHash', full_name='proto.TransactionReceipt.topicRunningHash', index=7,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topicRunningHashVersion', full_name='proto.TransactionReceipt.topicRunningHashVersion', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=429,
)

_TRANSACTIONRECEIPT.fields_by_name['status'].enum_type = ResponseCode__pb2._RESPONSECODEENUM
_TRANSACTIONRECEIPT.fields_by_name['accountID'].message_type = BasicTypes__pb2._ACCOUNTID
_TRANSACTIONRECEIPT.fields_by_name['fileID'].message_type = BasicTypes__pb2._FILEID
_TRANSACTIONRECEIPT.fields_by_name['contractID'].message_type = BasicTypes__pb2._CONTRACTID
_TRANSACTIONRECEIPT.fields_by_name['exchangeRate'].message_type = ExchangeRate__pb2._EXCHANGERATESET
_TRANSACTIONRECEIPT.fields_by_name['topicID'].message_type = BasicTypes__pb2._TOPICID
DESCRIPTOR.message_types_by_name['TransactionReceipt'] = _TRANSACTIONRECEIPT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionReceipt = _reflection.GeneratedProtocolMessageType('TransactionReceipt', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONRECEIPT,
  '__module__' : 'TransactionReceipt_pb2'
  # @@protoc_insertion_point(class_scope:proto.TransactionReceipt)
  })
_sym_db.RegisterMessage(TransactionReceipt)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
