# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransactionGetRecord.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransactionRecord_pb2 as TransactionRecord__pb2
import BasicTypes_pb2 as BasicTypes__pb2
import QueryHeader_pb2 as QueryHeader__pb2
import ResponseHeader_pb2 as ResponseHeader__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TransactionGetRecord.proto',
  package='proto',
  syntax='proto3',
  serialized_options=b'\n\032com.hedera.hashgraph.protoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1aTransactionGetRecord.proto\x12\x05proto\x1a\x17TransactionRecord.proto\x1a\x10\x42\x61sicTypes.proto\x1a\x11QueryHeader.proto\x1a\x14ResponseHeader.proto\"l\n\x19TransactionGetRecordQuery\x12\"\n\x06header\x18\x01 \x01(\x0b\x32\x12.proto.QueryHeader\x12+\n\rtransactionID\x18\x02 \x01(\x0b\x32\x14.proto.TransactionID\"z\n\x1cTransactionGetRecordResponse\x12%\n\x06header\x18\x01 \x01(\x0b\x32\x15.proto.ResponseHeader\x12\x33\n\x11transactionRecord\x18\x03 \x01(\x0b\x32\x18.proto.TransactionRecordB\x1e\n\x1a\x63om.hedera.hashgraph.protoP\x01\x62\x06proto3'
  ,
  dependencies=[TransactionRecord__pb2.DESCRIPTOR,BasicTypes__pb2.DESCRIPTOR,QueryHeader__pb2.DESCRIPTOR,ResponseHeader__pb2.DESCRIPTOR,])




_TRANSACTIONGETRECORDQUERY = _descriptor.Descriptor(
  name='TransactionGetRecordQuery',
  full_name='proto.TransactionGetRecordQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.TransactionGetRecordQuery.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactionID', full_name='proto.TransactionGetRecordQuery.transactionID', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=229,
)


_TRANSACTIONGETRECORDRESPONSE = _descriptor.Descriptor(
  name='TransactionGetRecordResponse',
  full_name='proto.TransactionGetRecordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='proto.TransactionGetRecordResponse.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transactionRecord', full_name='proto.TransactionGetRecordResponse.transactionRecord', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=231,
  serialized_end=353,
)

_TRANSACTIONGETRECORDQUERY.fields_by_name['header'].message_type = QueryHeader__pb2._QUERYHEADER
_TRANSACTIONGETRECORDQUERY.fields_by_name['transactionID'].message_type = BasicTypes__pb2._TRANSACTIONID
_TRANSACTIONGETRECORDRESPONSE.fields_by_name['header'].message_type = ResponseHeader__pb2._RESPONSEHEADER
_TRANSACTIONGETRECORDRESPONSE.fields_by_name['transactionRecord'].message_type = TransactionRecord__pb2._TRANSACTIONRECORD
DESCRIPTOR.message_types_by_name['TransactionGetRecordQuery'] = _TRANSACTIONGETRECORDQUERY
DESCRIPTOR.message_types_by_name['TransactionGetRecordResponse'] = _TRANSACTIONGETRECORDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransactionGetRecordQuery = _reflection.GeneratedProtocolMessageType('TransactionGetRecordQuery', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONGETRECORDQUERY,
  '__module__' : 'TransactionGetRecord_pb2'
  # @@protoc_insertion_point(class_scope:proto.TransactionGetRecordQuery)
  })
_sym_db.RegisterMessage(TransactionGetRecordQuery)

TransactionGetRecordResponse = _reflection.GeneratedProtocolMessageType('TransactionGetRecordResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRANSACTIONGETRECORDRESPONSE,
  '__module__' : 'TransactionGetRecord_pb2'
  # @@protoc_insertion_point(class_scope:proto.TransactionGetRecordResponse)
  })
_sym_db.RegisterMessage(TransactionGetRecordResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
